/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Nathaly
 */

import control.GestorSistema;
import modelo.fs.*;               // SistemaArchivos, Directorio, NodoFS, Archivo, ListaEnlazada, etc.
import javax.swing.tree.TreeModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.util.Random;
import java.awt.BorderLayout;

public class VentanaPrincipal extends javax.swing.JFrame {

    private GestorSistema gestor;
    private ModeloTablaAsignacion modeloTabla;
    private PanelDisco panelDiscoDibujo;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        setTitle("Simulador de Sistema de Archivos");

        // Crear el backend
        gestor = new GestorSistema(50);
        inicializarFSInicial();  // crea DocsA, DocsB y 10 archivos aleatorios

        // Conectar árbol al sistema de archivos real
        treeFS.setModel(construirModeloArbol());

        // Conectar tabla de asignación
        modeloTabla = new ModeloTablaAsignacion(gestor.getSistemaArchivos());
        tableAsignacion.setModel(modeloTabla);

        // Conectar panel de disco (dibujo)
        panelDisco.setLayout(new BorderLayout());
        panelDiscoDibujo = new PanelDisco(gestor.getSistemaArchivos());
        panelDisco.add(panelDiscoDibujo, BorderLayout.CENTER);

        // Ajustar tamaño inicial de los split panes (opcional)
        splitFS.setDividerLocation(0.3);
        splitDerechaFS.setDividerLocation(0.5);
    }

    // ============ MÉTODO: estado inicial del FS ============
    private void inicializarFSInicial() {
        SistemaArchivos sa = gestor.getSistemaArchivos();
        Directorio root = sa.getRaiz();

        sa.crearDirectorio(root, "DocsA");
        sa.crearDirectorio(root, "DocsB");

        String[] extensiones = { ".txt", ".log", ".dat", ".csv", ".jpg", ".bin" };
        Random rnd = new Random();

        for (int i = 1; i <= 10; i++) {
            String base = "auto_" + i;
            String ext = extensiones[rnd.nextInt(extensiones.length)];
            int tam = 1 + rnd.nextInt(8); // 1 a 8 bloques

            boolean enA = rnd.nextBoolean();
            String rutaDir = enA ? "/root/DocsA" : "/root/DocsB";
            String rutaArchivo = rutaDir + "/" + base + ext;

            boolean ok = gestor.solicitarCrearArchivo(rutaArchivo, tam);
            if (ok) gestor.ejecutarPaso();
        }
    }

    // ============ MÉTODOS: construir modelo del árbol ============
    private TreeModel construirModeloArbol() {
        SistemaArchivos sa = gestor.getSistemaArchivos();
        Directorio raiz = sa.getRaiz();

        DefaultMutableTreeNode nodoRoot = construirNodoRec(raiz, "/root");
        return new DefaultTreeModel(nodoRoot);
    }

    private DefaultMutableTreeNode construirNodoRec(Directorio dir, String rutaActual) {
        DefaultMutableTreeNode nodoDir = new DefaultMutableTreeNode(rutaActual);

        ListaEnlazada<NodoFS> hijos = dir.getHijos();
        for (int i = 0; i < hijos.size(); i++) {
            NodoFS hijo = hijos.get(i);
            if (hijo.esDirectorio()) {
                Directorio sub = (Directorio) hijo;
                String rutaHijo = rutaActual + "/" + sub.getNombre();
                nodoDir.add(construirNodoRec(sub, rutaHijo));
            } else {
                Archivo a = (Archivo) hijo;
                String rutaArchivo = rutaActual + "/" + a.getNombre();
                nodoDir.add(new DefaultMutableTreeNode(rutaArchivo));
            }
        }
        return nodoDir;
    }

    // ============ MÉTODO: refrescar toda la pestaña de FS ============
    private void refrescarTodo() {
        treeFS.setModel(construirModeloArbol());
        modeloTabla.fireTableDataChanged();
        panelDiscoDibujo.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPrincipal = new javax.swing.JTabbedPane();
        panelFS = new javax.swing.JPanel();
        splitFS = new javax.swing.JSplitPane();
        scrollArbol = new javax.swing.JScrollPane();
        treeFS = new javax.swing.JTree();
        splitDerechaFS = new javax.swing.JSplitPane();
        scrollTablaAsignacion = new javax.swing.JScrollPane();
        tableAsignacion = new javax.swing.JTable();
        panelDisco = new javax.swing.JPanel();
        panelControles = new javax.swing.JPanel();
        panelCola = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFS.setLayout(new java.awt.BorderLayout());

        scrollArbol.setViewportView(treeFS);

        splitFS.setLeftComponent(scrollArbol);

        splitDerechaFS.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tableAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTablaAsignacion.setViewportView(tableAsignacion);

        splitDerechaFS.setTopComponent(scrollTablaAsignacion);

        javax.swing.GroupLayout panelDiscoLayout = new javax.swing.GroupLayout(panelDisco);
        panelDisco.setLayout(panelDiscoLayout);
        panelDiscoLayout.setHorizontalGroup(
            panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        panelDiscoLayout.setVerticalGroup(
            panelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        splitDerechaFS.setRightComponent(panelDisco);

        splitFS.setRightComponent(splitDerechaFS);

        panelFS.add(splitFS, java.awt.BorderLayout.CENTER);

        tabbedPrincipal.addTab("Sistema de Archivos", panelFS);
        tabbedPrincipal.addTab("Controles", panelControles);

        panelCola.setLayout(new java.awt.BorderLayout());
        tabbedPrincipal.addTab("Cola de procesos", panelCola);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCola;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelDisco;
    private javax.swing.JPanel panelFS;
    private javax.swing.JScrollPane scrollArbol;
    private javax.swing.JScrollPane scrollTablaAsignacion;
    private javax.swing.JSplitPane splitDerechaFS;
    private javax.swing.JSplitPane splitFS;
    private javax.swing.JTabbedPane tabbedPrincipal;
    private javax.swing.JTable tableAsignacion;
    private javax.swing.JTree treeFS;
    // End of variables declaration//GEN-END:variables
}
